FROM ruby:2.4
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /fisbook-web
WORKDIR /fisbook-web
ADD Gemfile /fisbook-web/Gemfile
ADD Gemfile.lock /fisbook-web/Gemfile.lock
RUN bundle install
ADD . /fisbook-web
