# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# development: &default
#   adapter: postgresql
#   encoding: unicode
#   database: fisbook_web_development
#   pool: 5
#
# test:
#   <<: *default
#   database: fisbook_web_test

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: development

# production:
#   <<: *default
#   database: db/production.sqlite3
production:
  adapter: postgresql
  encoding: unicode
  database: fisbook-web_production
  pool: 5
